authors/urls.py
from django.urls import path
from .views import *
from django.views.decorators.cache import cache_page
from django.contrib import admin
app_name = "authors"

urlpatterns = [
   path('', cache_page(3 * 1)(PostsList.as_view()), name='home'),
   path('admin/', cache_page(3 * 1)(PostsList.as_view()), name='admin'),
   path('PostList/', AuthorList.as_view(), name="post_list"),
   path('posts/', PostsList.as_view(), name="posts"),
   path('search/', PostsSearch.as_view(), name="search"),
   # path('post/', PostDetail.as_view(), name="post"),
   # path('news/', PostDetail.as_view(), name="news"),
   path('create/', NewsCreate.as_view(), name='create'),
   path('News-Create/', NewsCreate.as_view(), name='news-create'),
   path('article/create/', NewsCreate.as_view(), name='article-create'),
   path('post/<int:pk>', PostDetail.as_view(), name='post'),
   path('news/edit/<int:pk>', PostFormView.as_view(), name='news-edit'),
   path('article/edit/<int:pk>', PostFormView.as_view(), name='article-edit'),
   path('news/delete/<int:pk>', PostDeleteView.as_view(), name='news-delete'),
   path('article/delete/<int:pk>', PostDeleteView.as_view(), name='article-delete'),
   path('/admin/', admin.site.urls),
   ]

authors/models.py
from django.db import models
from django.conf import settings
from django.db.models import Sum
from django.contrib.auth.models import User

from . import TYPE_CHOICES

article = 'A'
news = 'N'

Types = [
    (article, 'статья'),
    (news, 'новость'),
]


class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='Имя')
    rating = models.IntegerField(default=0, verbose_name='Рейтинг')

    def update_rating(self):
        my_posts = self.posts.all()
        post_comments = [p.post_comments.aggregate(sum=Sum('rating'))['sum'] for p in my_posts]
        post_comments = sum(post_comments)
        posts = self.posts.values('rating')
        posts = sum(p['rating'] for p in posts) * 3
        comments = self.user.comments.values('rating')
        comments = sum(c['rating'] for c in comments)
        self.rating = posts + comments + post_comments

class Category(models.Model):
    name = models.CharField(unique=True, max_length=256, verbose_name='Название')


class Post(models.Model):
    article = 'A'
    news = 'N'
    author = models.ForeignKey(Author, related_name='posts', on_delete=models.CASCADE, verbose_name='Автор')
    categories = models.ManyToManyField(Category, verbose_name='Категория')
    type = models.CharField(max_length=1, choices=TYPE_CHOICES)
    title = models.CharField(unique=True, max_length=256, verbose_name='Название')
    text = models.TextField()
    rating = models.IntegerField(default=0, verbose_name='Рейтинг')
    created_at = models.DateTimeField(auto_now_add=True, null=True, verbose_name='Рейтинг больше, чем')
    updated_at = models.DateTimeField(auto_now=True, null=True, verbose_name='Создан ранее, чем')


    def preview(self):
        return self.text[:124] + '...' if len(self.text) > 124 else self.text



    def like(self):
        self.rating += 1

    def dislike(self):
        self.rating -= 1





class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,related_name='Посты' )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='Автор', on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True, null=True, verbose_name='Рейтинг больше, чем')
    updated_at = models.DateTimeField(auto_now=True, null=True, verbose_name='Создан ранее, чем')
    rating = models.IntegerField(default=0)


    def like(self):
        self.rating += 1

    def dislike(self):
        self.rating -= 1




authors/forms.py
#Coding=UTF-8
from django import forms
from django.core.exceptions import ValidationError
from .models import Post, Author


# from .models import *

class AddPostForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['cat'].empty_label = "Категория не выбрана"

    class Meta:
        model = Post
        fields = ['title', 'author', 'categories', 'type', 'content', 'text', 'rating',]
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-input'}),
            'content': forms.Textarea(attrs={'cols': 60, 'rows': 10}),
        }

    def clean_title(self):
        title = self.cleaned_data['title']
        if len(title) > 200:
            raise ValidationError('Длина превышает 200 символов')

        return title


class PostForm(forms.Form):
    title = forms.CharField()
    text = forms.CharField(widget=forms.Textarea)

authors/views.py
################# news from
# импорты django
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, View
from django.urls import reverse_lazy
# группа импорта для реализации механизма добавления в группу пользователя через реадктирование профиля на портале
# с использованием библиотеки allauth
from django.shortcuts import redirect
from pyexpat.errors import messages

# from .forms import AddPostForm
# from project.simpleapp.models import Product
# импорты проекта
from .models import Post, Author
from .forms import PostForm
from django.contrib.auth.models import User
from .filters import PostFilter
# Настройки включения перевода
from django.utils.translation import gettext as _ # импортируем функцию перевода
# ограничение на количество публикаций в день для автора
LIMIT_POSTS = 20
# пример создания вьюшки через класс - исключительно в целях тестирования реализации перевода


class IndexTrans(View):
    def get(self, request):
        string = _("Test string")
        return HttpResponse(string)


# Пример реализации вьюшки через класс  для обучения настройки изменения таймзоны
class IndexTimezone(View):
    def get(self, request):
        # Код ниже перенесен в контекстынй процессор context_processors.py
        # user_timezone = pytz.timezone(request.session.get('django_timezone') or settings.TIME_ZONE)
        # current_time = timezone.now().astimezone(user_timezone)
        #
        # context = {
        #     'current_time': current_time,
        #     'timezones': pytz.common_timezones #  добавляем в контекст все доступные часовые пояса
        # }
        return HttpResponse(render(request, 'flatpages/default.html', {}))

    #  по пост-запросу будем добавлять в сессию часовой пояс, который и будет обрабатываться написанным нами ранее middleware
    def post(self, request):
        request.session['django_timezone'] = request.POST['timezone']
        return redirect('index_test')

#######
menu = [{'title': "О сайте", 'url_name': 'about'},
        {'title': "Добавить статью", 'url_name': 'add_page'},
        {'title': "Обратная связь", 'url_name': 'contact'},
        {'title': "Войти", 'url_name': 'login'}
]


class AuthorList(ListView):
    model = Author
    context_object_name = 'Authors'
    template_name = 'authors.html'
    queryset = Author.objects.all()
    post = ['title', 'text']

class PostsList(ListView):
    model = Post
    ordering = '-created_at'
    template_name = 'posts.html'
    context_object_name = 'posts'
    paginate_by = 6

    def get_queryset(self):
        queryset = super().get_queryset()

        self.filterset = PostFilter(self.request.GET, queryset)

        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filterset'] = self.filterset
        return context

# class PostDetail(DetailView):
#     model = Post
#     template_name = 'post.html'
#     context_object_name = 'post'
#     queryset = Post.objects.all()

#################
class PostDetail(DetailView):
    model = Post
    template_name = 'post.html'
    #slug_url_kwarg = 'post_slug'
    context_object_name = 'post'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = context['post']
        context['menu'] = menu
        return context



class PostsSearch(ListView):
    model = Post
    ordering = '-created_at'
    template_name = 'search.html'
    context_object_name = 'posts'
    paginate_by = 6

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = PostFilter(self.request.GET, queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['filterset'] = self.filterset
        return context


class NewsCreate(LoginRequiredMixin, CreateView):
    permission_required = ('simpleapp.add_post',)
    form_class = PostForm
    model = Post
    template_name = 'post_edit.html'

    # def form_valid(self, form):
    #     author = Author.objects.filter(user=self.request.user.id).first()
    #     if not author:
    #         author = Author.objects.first()
    #         messages.error(self.request, "You not author, we get first.")
    #     else:
    #         messages.success(self.request, "The task was created successfully.")
    #     form.instance.author = author
    #     form.instance.type = 'N'
    #
    #     return super(NewsCreate, self).form_valid(form)
################
# class NewsCreate(CreateView):
#     model = Post
#     fields = ['categories', 'title', 'text']
#     template_name = 'addpage.html'
#     success_url = reverse_lazy('home')
#
#     def get_context_data(self, *, object_list=None, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['title'] = 'Добавление статьи'
#         context['menu'] = menu
#         return context
#####
# def addpage(request):
#     if request.method == 'POST':
#         form = AddPostForm(request.POST, request.FILES)
#         if form.is_valid():
#             #print(form.cleaned_data)
#             form.save()
#             return redirect('home')
#     else:
#         form = AddPostForm()
#     return render(request, 'addpage.html', {'form': form, 'menu': menu, 'title': 'Добавление статьи'})
#

class ArticleCreate(CreateView):
    model = Post
    fields = ['categories', 'title', 'text']
    success_url = reverse_lazy('authors:posts')

    def form_valid(self, form):
        author = Author.objects.filter(user=self.request.user.id).first()
        if not author:
            author = Author.objects.first()
            messages.error(self.request, "You not author, we get first.")
        else:
            messages.success(self.request, "The task was created successfully.")
        form.instance.author = author
        form.instance.type = 'A'

        return super(ArticleCreate, self).form_valid(form)

class PostFormView(UpdateView):
    permission_required = ('simpleapp.change_post',)
    form_class = PostForm
    model = Post
    template_name = 'post_edit.html'

class PostDeleteView(DeleteView):
    permission_required = ('simpleapp.delete_post',)
    model = Post
    template_name = 'post_delete.html'
    success_url = reverse_lazy('post_list')

class Post(View):
    model = Post
    success_url = reverse_lazy('authors:post')
    template_name = 'authors/post.html'


def cat_detail(request, category_id):
    category = Category.objects.get(id=category_id)
    products = Product.objects.filter(category=category)
    paginator = Paginator(products, 3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'product/cat_detail.html',
         {'category': category, 'products': products, 'page_obj': page_obj})

authors/templates/authors/addpage..html
{% extends 'flatpages/default.html' %}
{% load censor %}
{% load censor custom_tags%}

{% block content %}
<h1>{{title}}</h1>

<form action="{% url 'add_page' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="form-error">{{ form.non_field_errors }}</div>

{% for f in post %}
<p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
<div class="form-error">{{ f.errors }}</div>
{% endfor %}


    <button type="submit">Добавить</button>
</form>

{% endblock %}

authors/templates/authors/authors.html
{% extends 'flatpages/default.html' %}
{% load censor %}


{% block title %}
Post {{post.title|my_censor}} - type {{ post.type }}
{% endblock title %}

{%block content%}

<h1>Список новостей</h1>

<h4>Всего новостей {{posts|length}}</h4>
	{% for post in posts %}
	<tr>{{posts|length}}</tr>
		<td>{{ post.user }}</td>
		<td>{{ post.created_at|date:'d M Y' }}</td>
		<td>{{ post.text|truncatewords:20 }}</td>
	</tr>
	{% endfor %}

   <hr>


<div class="center">
	<form method="post" novalidate class="card">
	 	{%csrf_token %}

	 	<h2>Post</h2>
		{% for field in form %}
			{% if field.name == 'completed' %}
				<p>
					{{ field.label_tag }}
					{{ field }}
				</p>
				{% if field.errors %}
	        		<small class="error">{{ field.errors|striptags  }}</small>
	        	{% endif %}
			{% else %}
	    		{{ field.label_tag }}
	        	{{ field }}
	        	{% if field.errors %}
	        		<small class="error">{{ field.errors|striptags  }}</small>
	        	{% endif %}
	        {% endif %}
		{% endfor %}

		<div class="form-buttons">
			<input type="submit" value="Save" class="btn btn-primary"/>
			<a href="{%url 'authors:posts' %}" class="btn btn-outline">Cancel</a>
		</div>
	</form>
</div>
<br> {{post.created_at|date:'d M Y'}} <br> {{ post.text|truncatechars:20|my_censor }}
<br> {{post.created_at|date:'d M Y'}} <br> {{ post.text|truncatechars:20|my_censor }}

<hr>

{% if page_obj.has_previous %}
       {# Для каждой ссылки пагинации указываем обработку через новый тег #}

       {% if page_obj.previous_page_number != 1 %}
           ...
           {{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       {{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           {{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}



{% endblock content %}

authors/templates/authors/confirm_delete.html

{% extends 'flatpages/default.html' %}

{%block content%}

<form method="post">{% csrf_token %}

<p>Are you sure you want to delete "{{ object }}"?</p>
<input type="submit" value="Confirm">

</form>

{%endblock content%}

authors/templates/authors/create.html
{% extends 'flatpages/default.html' %}
{% load censor %}
{% load censor custom_tags%}

{% block title %}
Posts
{% endblock title %}


{% block content %}
<form action="" method="get">
       {{ filterset.form.as_p }}
       <input type="submit" value="Найти" />
   </form>
<h1>Все статьи {{posts|length}}</h1>
{% for post in posts %}
<a href="{% url 'authors:post' pk=post.pk %}">{{ post.title|my_censor }}</a>
<br> {{post.created_at|date:'d M Y'}} <br> {{ post.text|truncatechars:20|my_censor }}<hr>
{% endfor %}
{% if page_obj.has_previous %}
       {# Для каждой ссылки пагинации указываем обработку через новый тег #}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

authors/templates/authors/edit_post.html
{% extends 'flatpages/default.html' %}

{%block content%}

  <form method="post">{% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Send message">
  </form>

{%endblock content%}

authors/templates/authors/home.html
{% extends 'flatpages/default.html' %}

{% block content %}
<div id="wb_Heading2" style="position:absolute;left:41px;top:1px;width:775px;height:155px;z-index:0;">
<h3 id="Heading2">{{ flatpage.content }}<br></h3></div>

<div id="wb_Heading1" style="position:absolute;left:41px;top:110px;width:775px;height:155px;z-index:0;">
<h3 id="Heading1">Всем привет.<br> Я обучаюсь в SkillFactory — oнлайн-школе IT-профессий на новую специальность Fullstack разработчик на Python<br></h3></div>

<div id="wb_Marquee1" style="position:absolute;left:41px;top:228px;width:675px;height:368px;text-align:center;z-index:1;overflow:hidden">
<h5 align="left" style="Marquee1">Необходимо выполнить следующие задания:<br>
    1.Создать проект Django.<br>
    2.Добавить в него 3 статические странички.<br>
    3.На одной из страниц контент повторяется 2 раза без изменения content (два раза прописано ""flatpage.content"").<br>
    4.Одна из страниц на сайте доступна только админу (только вошедшему пользователю).<br>
    5.На одной из страниц изменены шрифты и размеры текста.<br>
    6.Сайт представляет собой оформленный Bootstrap-шаблон со встроенными пользовательскими данными.<br>
    7.Статические файлы Bootstrap загружаются через теги "% load static %" и "% static %".<br><br></h5>

<div id="wb_Marquee2" style="position:absolute;left:16px;top:300px;width:675px;height:368px;text-align:center;z-index:1;overflow:hidden">
<h6 align="left" style="Marquee2">SkillFactory — oнлайн-школа IT -профессий. Онлайн-курсы по Data Science,
    аналитике, программированию и менеджменту © 2023</h6></div>

{% endblock content %}

authors/templates/authors/index.html
<!DOCTYPE html>
<html lang="en">
</html>

authors/templates/authors/news.html
{% extends 'flatpages/default.html' %}
{% load censor %}
{% load censor custom_filters %}
{% load censor custom_tags%}

{% block title %}
News
{% endblock title %}

{% block content %}
   <h1>{% 'Список новостей' %}</h1>

   <h4>{% trans 'Всего новостей' %} {{news|length}} </h4>

   <hr>
   {% if news %}
       <table>
           <tr>
               <td>{% trans 'Заголовок' %}</td>
               <td>{% trans 'Дата публикации' %}</td>
               <td>{% trans 'Содержание' %}</td>
           </tr>

           {% for post in news %}
           <tr>
               <td>{{ post.header|censors }}</td>
               <td>{{ post.datetime_post|date:'d M Y' }}</td>
               <td>{{ post.content|censors|truncatewords:20 }}</td>
           </tr>
           {% endfor %}
    <form action="/subscribe/post/">
        <input type="submit" value="{% trans 'Подписаться на новинки в категории' %}">
    </form>
       </table>
   {% else %}
       <h2>Новостей нет!</h2>
   {% endif %}

   {# Информация о предыдущих страницах #}
   {% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}


{% endblock content %}

authors/templates/authors/post.html
{% extends 'flatpages/default.html' %}
{% load censor %}


{% block title %}
Post {{post.title|my_censor}} - type {{ post.type }}
{% endblock title %}


{% block content %}
<h1>{{post.title|my_censor}}</h1><span>{{post.author.user.username}}</span>
<br> {{ post.text|my_censor }} <br> rating {{post.rating}} <br> {{post.created_at|date:'d M Y'}}<hr>
<hr>
<h2>категории:</h2>
{% for category in post.categories.all %}
<span>{{category.name}}</span>
{% endfor %}
{{post.content|linebreaks}}
{% endblock content %}

authors/templates/authors/post_form.html
{% extends 'flatpages/default.html' %}

{%block content%}

<div class="center">
	<form method="post" novalidate class="card">
	 	{%csrf_token %}

	 	<h2>Post</h2>
		{% for field in form %}
			{% if field.name == 'completed' %}
				<p>
					{{ field.label_tag }}
					{{ field }}
				</p>
				{% if field.errors %}
	        		<small class="error">{{ field.errors|striptags  }}</small>
	        	{% endif %}
			{% else %}
	    		{{ field.label_tag }}
	        	{{ field }}
	        	{% if field.errors %}
	        		<small class="error">{{ field.errors|striptags  }}</small>
	        	{% endif %}
	        {% endif %}
		{% endfor %}

		<div class="form-buttons">
			<input type="submit" value="Save" class="btn btn-primary"/>
			<a href="{%url 'authors:posts' %}" class="btn btn-outline">Cancel</a>
		</div>
	</form>
</div>

{%endblock content%}

authors/templates/authors/post_list.html
{% extends 'flatpages/default.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Тестовая страница-Post</title>
</head>
<body>
<div id="wb_Heading2" style="position:absolute;left:41px;top:1px;width:775px;height:155px;z-index:0;">
<h3 id="Heading2">{{ flatpage.content }}<br></h3></div>
<div id="wb_Heading1" style="position:absolute;left:41px;top:110px;width:775px;height:155px;z-index:0;">
<h3 id="Heading1">Всем привет.<br> Я обучаюсь в SkillFactory — oнлайн-школе IT-профессий на новую специальность Fullstack разработчик на Python<br></h3></div>

<div id="wb_Marquee1" style="position:absolute;left:41px;top:228px;width:675px;height:368px;text-align:center;z-index:1;overflow:hidden">
<h5 align="left" style="Marquee1">Необходимо выполнить следующие задания:<br>
    1.Создать проект Django.<br>
    2.Добавить в него 3 статические странички.<br>
    3.На одной из страниц контент повторяется 2 раза без изменения content (два раза прописано ""flatpage.content"").<br>
    4.Одна из страниц на сайте доступна только админу (только вошедшему пользователю).<br>
    5.На одной из страниц изменены шрифты и размеры текста.<br>
    6.Сайт представляет собой оформленный Bootstrap-шаблон со встроенными пользовательскими данными.<br>
    7.Статические файлы Bootstrap загружаются через теги "% load static %" и "% static %".<br><br></h5>

<div id="wb_Marquee2" style="position:absolute;left:16px;top:300px;width:675px;height:368px;text-align:center;z-index:1;overflow:hidden">
<h6 align="left" style="Marquee2">SkillFactory — oнлайн-школа IT -профессий. Онлайн-курсы по Data Science,
    аналитике, программированию и менеджменту © 2023</h6></div>

</body>
</html>




authors/templates/authors/posts.html

{% extends 'flatpages/default.html' %}
{% load censor %}
{% load censor custom_tags%}

{% block title %}
Posts
{% endblock title %}


{% block content %}
<form action="" method="get">


   </form>
<h2>Все статьи {{posts|length}}</h2>
{% for post in posts %}
<p><a href="{% url 'authors:post' pk=post.pk %}">{{ post.title|my_censor }}</a>
{% if post.type == 'A' %}
    <a href="{% url 'authors:article-edit' pk=post.pk %}">Редактировать</a>
    <a href="{% url 'authors:article-delete' pk=post.pk %}">Удалить</a>
{% else %}
    <a href="{% url 'authors:news-edit' pk=post.pk %}">Редактировать</a>
    <a href="{% url 'authors:news-delete' pk=post.pk %}">Удалить</a>
{% endif %}

    </p>
<br> {{post.created_at|date:'d M Y'}} <br> {{ post.text|truncatechars:240|my_censor }}

<hr>
{% endfor %}
{% if page_obj.has_previous %}
       {# Для каждой ссылки пагинации указываем обработку через новый тег #}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

authors/templates/authors/search.html
{% extends 'flatpages/default.html' %}
{% load censor %}
{% load censor custom_tags%}

{% block title %}
Posts
{% endblock title %}


{% block content %}
<form action="" method="get">
       {{ filterset.form.as_p }}
       <input type="submit" value="Найти" />
   </form>
<h2>Все статьи {{posts|length}}</h2>
{% for post in posts %}
<a href="{% url 'authors:post' pk=post.pk %}">{{ post.title|my_censor }}</a>
<br> {{post.created_at|date:'d M Y'}} <br> {{ post.text|truncatechars:240|my_censor }}<hr>
{% endfor %}
{% if page_obj.has_previous %}
       {# Для каждой ссылки пагинации указываем обработку через новый тег #}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}